name: Combined CI
on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  REGISTRY_IMAGE: ${{ github.repository_owner }}/pos2

permissions:
  contents: read
  packages: write

jobs:
  build-supervisor:
    name: Build supervisor
    strategy:
      fail-fast: false
      matrix:
        include:
          - architecture: amd64
            runner: ubuntu-24.04
          - architecture: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Log into github container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY}}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REGISTRY_IMAGE }}
          tags: |
            type=sha,prefix=supervisor-sha-
      - name: Build container
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile.dockerloader.ci
          build-args: |
            TARGETARCH=${{ matrix.architecture }}
          platforms: linux/${{ matrix.architecture }}
          labels: ${{ steps.meta.outputs.labels}}
          tags: ${{ steps.meta.outputs.tags }}
          push: true
      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.push.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"
      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-supervisor-linux-${{ matrix.architecture }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  build-runtime:
    name: Build runtime
    strategy:
      fail-fast: false
      matrix:
        include:
          - architecture: amd64
            runner: ubuntu-24.04
          - architecture: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Log into github container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY}}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REGISTRY_IMAGE }}
          tags: |
            type=sha,prefix=runtime-sha-
      - name: Build container
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile.wasi3experiment.ci
          build-args: |
            TARGETARCH=${{ matrix.architecture }}
          platforms: linux/${{ matrix.architecture }}
          labels: ${{ steps.meta.outputs.labels}}
          tags: ${{ steps.meta.outputs.tags }}
          push: true
      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.push.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"
      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-runtime-linux-${{ matrix.architecture }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  combine:
    name: Combine multiarch manifests
    runs-on: ubuntu-24.04
    needs: [build-supervisor, build-runtime]
    steps:
      - name: Download supervisor digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/supervisor-digests
          pattern: digests-supervisor-*
          merge-multiple: true
      - name: Download runtime digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/runtime-digests
          pattern: digests-runtime-*
          merge-multiple: true
      - name: Log into github container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY}}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Get supervisor metadata
        id: supervisor-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REGISTRY_IMAGE }}
          tags: |
            type=ref,event=branch,prefix=supervisor-
            type=sha,prefix=supervisor-sha-
      - name: Create supervisor manifest
        working-directory: ${{ runner.temp }}/supervisor-digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY }}/${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)
        env:
          DOCKER_METADATA_OUTPUT_JSON: ${{ steps.supervisor-meta.outputs.json }}
      - name: Inspect supervisor image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ env.REGISTRY_IMAGE }}:supervisor-main

      - name: Get runtime metadata
        id: runtime-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REGISTRY_IMAGE }}
          tags: |
            type=ref,event=branch,prefix=runtime-
            type=sha,prefix=runtime-sha-
      - name: Create runtime manifest
        working-directory: ${{ runner.temp }}/runtime-digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY }}/${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)
        env:
          DOCKER_METADATA_OUTPUT_JSON: ${{ steps.runtime-meta.outputs.json }}
      - name: Inspect runtime image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ env.REGISTRY_IMAGE }}:runtime-main
